name = "End phase"
weight = 1

blocks = [
    "1xminecraft:end_stone"
]

trades = [
    "trade:blocks-3"
]

[unlock]
blocks = 1500
command = false
game-time = -1
unlock-time = 36000

[on-unlock]
trades = [
    "2xminecraft:shulker_shell; 16-32xminecraft:diamond; 4-6",
    "1xminecraft:chorus_fruit; 16-32xminecraft:gold_ingot; 4-6",
    "8xminecraft:end_stone; 16-32xminecraft:iron_ingot; 4-6"
]
