name = "Cave phase"
weight = 2

starting-blocks = [
    "neoblock:chest:tier2-chest"
]

blocks = [
    "minecraft:iron_ore",
    "minecraft:gold_ore",
    "minecraft:coal_ore",
    "minecraft:copper_ore"
]

trades = [
    "trade:most-saplings",
    "trade:farm-2",
    "trade:mobs-2 50%",
    "trade:blocks-1"
]

[unlock]
blocks = 150
command = false
game-time = -1
unlock-time = 3600

[on-research]
trades = [
    "6xminecraft:gravel; 8xminecraft:cobblestone; 64",
    "5xminecraft:sand; 8xminecraft:cobblestone; 64",
    "4xminecraft:red_sand; 8xminecraft:cobblestone; 64",
    "1xminecraft:spruce_sapling; 10-20xminecraft:oak_log; 48-64xminecraft:dirt; 4-8"
]
