name = "Nether phase"
weight = 1

starting-blocks = [
    "neoblock:chest:tier4-chest"
]

blocks = [
    "10xminecraft:netherrack",
    "10x#neoblock:netherracks",     # Tag key defined in tags.toml
    "16xminecraft:basalt",
    "12xminecraft:blackstone",
    "4xminecraft:soul_sand",
    "2xminecraft:soul_soil",
    "2xminecraft:glowstone",
    "2xminecraft:magma_block",
    "2xminecraft:nether_quartz_ore",
    "2xminecraft:nether_gold_ore",
    "1xminecraft:ancient_debris",
    "1xminecraft:obsidian"
]

trades = [
    "trade:farm-4",
    "trade:mobs-4",
    "trade:blocks-2 80%"
]

[unlock]
blocks = 600
command = false
game-time = -1
unlock-time = 18000

[on-research]
trades = [
    "3-6xminecraft:warped_nylium; 8-16xminecraft:netherrack; 12-24",
    "3-6xminecraft:crimson_nylium; 8-16xminecraft:netherrack; 12-24",
    "3-6xminecraft:warped_fungus; 1-2xminecraft:warped_nylium; 10-20xminecraft:oak_sapling; 4-12",
    "3-6xminecraft:crimson_fungus; 1-2xminecraft:crimson_nylium; 10-20xminecraft:oak_sapling; 4-12"
]
