# Amount of blocks broken to unlock.
unlock = 600   # Nether phase
# Upgrade time in ticks. During upgrade the NeoBlock will turn into Bedrock.
unlock-time = 18000
# List of all blocks in this tier. All of them have equal chance to be chosen in this tier.
# Note that, blocks from tier 0 are available
blocks = [
    "20xminecraft:netherrack",
    "16xminecraft:basalt",
    "12xminecraft:blackstone",
    "4xminecraft:soul_sand",
    "2xminecraft:soul_soil",
    "2xminecraft:glowstone",
    "2xminecraft:magma_block",
    "2xminecraft:nether_quartz_ore",
    "2xminecraft:nether_gold_ore",
    "1xminecraft:ancient_debris",
    "1xminecraft:obsidian"
]
# The wight of tier when choosing between unlocked tiers.
weight = 1
# The trades the trader will spawn with when this tier is unlocked. This trader will despawn (if not dead) upon unlocking next tier.
# Syntax for item is `COUNT`x`ID`, the count can be a range like `8-12` or a number.
# Uses also use same syntax as the count, but not providing it will use 1 instead.
# For a trade use one of the following:
#    `RESULT`; `COST A`; `COST B`; `USES`
#    `RESULT`; `COST A`; `COST B`;
#    `RESULT`; `COST A`; `USES`
#    `RESULT`; `COST A`;
unlock-trades = [
    "3-6xminecraft:warped_nylium; 8-16xminecraft:netherrack; 12-24",
    "3-6xminecraft:crimson_nylium; 8-16xminecraft:netherrack; 12-24",
    "3-6xminecraft:warped_fungus; 1-2xminecraft:warped_nylium; 10-20xminecraft:oak_sapling; 4-12",
    "3-6xminecraft:crimson_fungus; 1-2xminecraft:crimson_nylium; 10-20xminecraft:oak_sapling; 4-12"
]
# Wandering NeoTraders will spawn when they have some offers
# List of offers they might have when spawned. using same syntax.
trader-trades = [
    "3-6xminecraft:warped_nylium; 8-16xminecraft:netherrack; 12-24",
    "3-6xminecraft:crimson_nylium; 8-16xminecraft:netherrack; 12-24",
    "1-2xminecraft:warped_fungus; 1-2xminecraft:warped_nylium; 10-20xminecraft:oak_sapling; 4-8",
    "1-2xminecraft:crimson_fungus; 1-2xminecraft:crimson_nylium; 10-20xminecraft:oak_sapling; 4-8",
    "1-2xminecraft:nether_wart; 8-12xminecraft:gold_ingot; 4-20xminecraft:soul_sand; 1-3",
    "1xminecraft:twisting_vines; 8-12xminecraft:gold_ingot; 4-20xminecraft:netherrack; 3",
    "1xminecraft:weeping_vines; 8-12xminecraft:gold_ingot; 4-20xminecraft:netherrack; 3",
    "8xminecraft:gilded_blackstone; 8xminecraft:gold_block; 16xminecraft:blackstone; 3",
    "mob:1xminecraft:fox; 16-32xminecraft:gold_ingot; 10-30xminecraft:sweet_berries; 2",
    "mob:1xminecraft:wolf; 16-32xminecraft:gold_ingot; 10-30xminecraft:bone; 2",
    "mob:1xminecraft:polar_bear; 16-32xminecraft:gold_ingot; 16-32xminecraft:cod; 2",
    "mob:1xminecraft:rabbit; 16-32xminecraft:gold_ingot; 16-32xminecraft:carrot; 2"
]
# Amount of trades they will choose from this tier
trader-count = 3
