modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/AGM-Studio/NeoBlock/issues"

[[mods]]
modId = "neoblock"
version = "${mod_version}"
displayName = "${mod_name}"

# A URL to query for updates for this mod. See the JSON update specification https://docs.neoforged.net/docs/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#logoFile = "logo.png"

displayURL = "https://www.curseforge.com/minecraft/mc-mods/neoblock"
credits = ""

authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.neoblock]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

# Here's another dependency
[[dependencies.neoblock]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
