# In this file you can list all blocks or items to be using a custom tag that only neoblock knows.
# You can use them like how you use the normal ones like #c:stones but with #neoblock:<name>
# Due the order of loading the configs, These lists won't be able to load other formats other than id
# For more lists add more keys to the list.
[items]
trims = [
    "minecraft:netherite_upgrade_smithing_template",
    "minecraft:sentry_armor_trim_smithing_template",
    "minecraft:vex_armor_trim_smithing_template",
    "minecraft:wild_armor_trim_smithing_template",
    "minecraft:coast_armor_trim_smithing_template",
    "minecraft:dune_armor_trim_smithing_template",
    "minecraft:wayfinder_armor_trim_smithing_template",
    "minecraft:raiser_armor_trim_smithing_template",
    "minecraft:sharper_armor_trim_smithing_template",
    "minecraft:host_armor_trim_smithing_template",
    "minecraft:ward_armor_trim_smithing_template",
    "minecraft:silence_armor_trim_smithing_template",
    "minecraft:tide_armor_trim_smithing_template",
    "minecraft:snout_armor_trim_smithing_template",
    "minecraft:rib_armor_trim_smithing_template",
    "minecraft:eye_armor_trim_smithing_template",
    "minecraft:spire_armor_trim_smithing_template",
    "minecraft:flow_armor_trim_smithing_template",
    "minecraft:bolt_armor_trim_smithing_template"
]

[blocks]
netherracks = [
    "minecraft:netherrack",
    "minecraft:crimson_nylium",
    "minecraft:warped_nylium"
]