name = "Growing phase"  # Helps you to check your tier with info command.
# Blocks you want to gurantee to be spawned when this tier is unlocked!
# The format is the same as blocks, also used in sequences.toml.
# If empty or missing, a random block will be chosen like normal.
starting-blocks = [
    "neoblock:chest:tier1-chest",
    "3xminecraft:stone"
]
# List of all blocks in this tier. All of them have equal chance to be chosen in this tier.
# Note that, blocks from tier 0 are available
blocks = [
    "10xminecraft:stone",
    "4xminecraft:coal_ore",
    "2xminecraft:iron_ore",
    "minecraft:andesite",
    "minecraft:granite",
    "minecraft:diorite",
    "minecraft:clay",
    "neoblock:chest:casual-chest",      # The chests are in chests.toml
    "neoblock:sequence:stone-pot",      # The sequences are in sequences.toml
    "neoblock:sequence:three-stones"
]
# The wight of tier when choosing between enabled tiers.
weight = 3
# The trades the trader will spawn with when this tier is enabled. This trader will despawn (if not dead) upon unlocking next tier.
# Syntax for item is `COUNT`x`ID`, the count can be a range like `8-12` or a number.
# Uses also use same syntax as the count, but not providing it will use 1 instead.
# For a trade use one of the following:
#    `RESULT`; `COST A`; `COST B`; `USES`
#    `RESULT`; `COST A`; `COST B`;
#    `RESULT`; `COST A`; `USES`
#    `RESULT`; `COST A`;
unlock-trades = [
    "trade:farm-1",
    "trade:oak-saplings",
    "1xminecraft:ice; 2-4xminecraft:oak_log; 8-16xminecraft:dirt; 8-12"
]
# Wandering NeoTraders will spawn when they have some offers
# List of offers they might have when spawned. using same syntax.
trades = [
    "trade:farm-1",
    "trade:mobs-1",
    "1xminecraft:ice; 2-4xminecraft:oak_log; 8-16xminecraft:dirt; 8-12 60%"
]

# Conditions to unlock the mod, all conditions must be met to unlock.
[unlock]
blocks = 50         # Amount of blocks needed to be broken, set to -1 to deactivate
command = false     # If server has to execute a command to unlock this.  /neoblock unlock <tier-number>
game-time = -1      # Amount of ticks world has been loaded, set to -1 to deactivate
unlock-time = 1200  # Upgrade time in ticks. During upgrade the NeoBlock will turn into Bedrock.